---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  warning = FALSE
)
```

# cmfproperty

This package analyzes property tax regressivity and produces various tables and figures for a sales ratio study.

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("erhla/cmfproperty")
```
## Example

This is the basic framework to conduct a sales ratio study:

```{r example}
library(cmfproperty)
df <- cmfproperty::example_data
df <-
  cmfproperty::reformat_data(
    df,
    sale_col = "SALE_PRICE",
    assessment_col = "ASSESSED_VALUE",
    sale_year_col = "SALE_YEAR",
    filter_data = TRUE
  )
stats <- cmfproperty::calc_iaao_stats(df)
head(stats)
```

More advanced features are available as well:
```{r example2}
cmfproperty::regression_tests(df)
```

```{r example3}
plot_ls <-
  cmfproperty::plots(stats,
                     df,
                     min_reporting_yr = 2006,
                     max_reporting_yr = 2016)
plot_ls[[1]]
plot_ls[[2]]
plot_ls[[3]]
plot_ls[[4]]
```

