---
title: "Figures"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Figures}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  warning = FALSE,
  comment = "#>"
)
```

This article produces a gallery of figures and tables produced by this package for reference.


```{r setup}
library(cmfproperty)

ratios <-
  cmfproperty::reformat_data(
    data = cmfproperty::example_data,
    sale_col = "SALE_PRICE",
    assessment_col = "ASSESSED_VALUE",
    sale_year_col = "SALE_YEAR",
  )
stats <- cmfproperty::calc_iaao_stats(ratios)
```

# calc_iaao_stats

```{r iaao_stats}
rmarkdown::paged_table(stats)
```

# regression_tests

```{r regression_tests, fig.width=6, results='asis'}
summary_info <-
  cmfproperty::regression_tests(ratios, produce_table = TRUE)
```

```{r}
kableExtra::kable(summary_info)
```


# iaao_graphs
```{r example1}
iaao_rslt <-
  cmfproperty::iaao_graphs(
    stats,
    ratios,
    min_reporting_yr = 2015,
    max_reporting_yr = 2019,
    jurisdiction_name = "Cook County, Illinois"
  )
```

## Coefficient of Dispersion (COD)

```{r codgraph, fig.width=6, fig.height=3}
print(iaao_rslt[[1]])
iaao_rslt[[2]]
```

## Price-Related Differential (PRD)
```{r prdgraph, fig.width=6, fig.height=3}
print(iaao_rslt[[3]])
iaao_rslt[[4]]
```

## Coefficient of Price-Related Bias (PRB)
```{r prbgraph, fig.width=6, fig.height=3}
print(iaao_rslt[[5]])
iaao_rslt[[6]]
```


# monte_carlo_graphs
```{r montecarlo_graphs, fig.width=6, fig.height=5}
m_rslts <- cmfproperty::monte_carlo_graphs(ratios)
gridExtra::grid.arrange(m_rslts[[1]],
                        m_rslts[[2]],
                        m_rslts[[3]],
                        m_rslts[[4]],
                        m_rslts[[5]],
                        m_rslts[[6]],
                        nrow = 3)
```

# diagnostic_plots
```{r diagnostic, fig.width=6, fig.height=4}
plots <-
  diagnostic_plots(stats,
                   ratios,
                   min_reporting_yr = 2015,
                   max_reporting_yr = 2019)
```

```{r}
plots[[1]]
```

```{r}
plots[[2]]
```

```{r}
plots[[3]]
```

```{r}
plots[[4]]
```

```{r}
plots[[5]]
```

```{r}
gridExtra::grid.arrange(plots[[6]],
                        plots[[7]],
                        plots[[8]],
                        plots[[9]],
                        ncol = 2,
                        nrow = 2)
```


# binned_scatter
```{r binned, fig.width=7, fig.height=4}
binned <- 
  cmfproperty::binned_scatter(
    ratios,
    min_reporting_yr = 2015,
    max_reporting_yr = 2019,
    jurisdiction_name = "Cook County, IL"
  )

print(binned[[1]])
binned[[2]]
```


# pct_over_under
```{r pct_over}
pct_over <-
  cmfproperty::pct_over_under(
    ratios,
    min_reporting_yr = 2015,
    max_reporting_yr = 2019,
    jurisdiction_name = "Cook County, IL"
  )

print(pct_over[[1]])
pct_over[[2]]
```


